# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/*.log

# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "filebeatlog-%{+yyyy.MM.dd}"

# setup.template.name: "filebeatlog"
# setup.template.pattern: "filebeatlog-*"
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - E:/ELK/samplelog.json
  json.keys_under_root: true
  json.add_error_key: true

output.logstash:
  hosts: ["your_logstash_host:5044"] 
