filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeatlog-%{+yyyy.MM.dd}"

setup.template.name: "filebeatlog"
setup.template.pattern: "filebeatlog-*"
